export enum EButtonStyleType {
  OUTLINE_RED = 'OUTLINE_RED',
  RED = 'RED',
  BLUE = 'BLUE',
  SHARK = 'SHARK',
  TEXT_RED = 'TEXT_RED',
  TEXT_HEATHER = 'TEXT_HEATHER',
  TRANSPARENT = 'TRANSPARENT',
  OUTER_SPACE = 'OUTER_SPACE',
  LIMED_SPRUCE = 'LIMED_SPRUCE',
}
